#!/usr/bin/env python3

import subprocess

def detect_olkb():
    """Returns whether an OLKB keyboard is connected to the computer.
    Requires: xinput, grep, wc."""
    proc1 = subprocess.Popen(['xinput', 'list'], stdout=subprocess.PIPE)
    proc2 = subprocess.Popen(['grep', 'OLKB'], stdin=proc1.stdout, stdout=subprocess.PIPE)
    proc3 = subprocess.Popen(['wc', '-l'], stdin=proc2.stdout, stdout=subprocess.PIPE)
    stdout, stderr = proc3.communicate()

    return not int(stdout) == 0

def laptopkb_id():
    return '17'

def disable_laptopkb():
    proc = subprocess.Popen(['xinput', 'float', laptopkb_id()])

def enable_laptopkb():
    proc = subprocess.Popen(['xinput', 'reattach', laptopkb_id(), '3'])

if __name__ == '__main__':
    if detect_olkb():
        disable_laptopkb()
        print('Laptop keyboard disabled')
    else:
        enable_laptopkb()
        print('Laptop keyboard enabled')
