#!/usr/bin/env python3

import subprocess, re

# laptop kb identifiers
IDENTIFIERS = ['Apple Internal Keyboard', 'AT Translated Set']

def detect_olkb():
    """Returns whether an OLKB keyboard is connected to the computer.
    Requires: xinput, grep, wc."""
    proc1 = subprocess.Popen(['xinput', 'list'], stdout=subprocess.PIPE)
    proc2 = subprocess.Popen(['grep', 'OLKB'], stdin=proc1.stdout, stdout=subprocess.PIPE)
    proc3 = subprocess.Popen(['wc', '-l'], stdin=proc2.stdout, stdout=subprocess.PIPE)
    stdout, stderr = proc3.communicate()

    return not int(stdout) == 0

def laptopkb_id():
    """Returns the xinput id of the laptop keyboard."""
    proc = subprocess.Popen(['xinput', 'list'], text=True, stdout=subprocess.PIPE)
    stdout, stderr = proc.communicate()

    pattern = '.*(' + '|'.join(IDENTIFIERS) + ').*id=([\d]*).*'
    match = re.search(pattern, stdout, re.IGNORECASE)
    if match:
        return match.group(2)

if __name__ == '__main__':
    laptopkb_id = laptopkb_id()
    if laptopkb_id is None:
        print('ERROR: could not determine id of laptopkb; check identifiers list.')
    elif detect_olkb():
        proc = subprocess.Popen(['xinput', 'float', laptopkb_id])
        print('laptop keyboard DISABLED')
    else:
        proc = subprocess.Popen(['xinput', 'reattach', laptopkb_id, '3'])
        print('laptop keyboard ENABLED')
        
