#!/usr/bin/env bash

if [[ $1 == "--help" ]] ; then
    echo "$(basename $0) - take screenshot"
    echo
    echo "USAGE:"
    echo " $(basename $0) [--clip]"
    echo
    echo "OPTIONS:"
    echo " --clip    Save screenshot to clipboard instead of ~/pics/screenshots"
elif [[ $1 == "--clip" ]] ; then
    # TODO: don't notify-send if maim is cancelled
    # note that using '&&' as below doesn't work bc the full command always returns 0
    maim -s -u | xclip -selection clipboard -t image/png 
    notify-send "sc" "screenshot saved to clipboard"
else
    IMG_PATH="$HOME/pics/screenshots/$(date +%m-%d-%y_%k:%M:%S).png"
    maim -s -u $IMG_PATH && notify-send "sc" "screenshot saved to $IMG_PATH" -t 10000
fi
