#!/usr/bin/env bash

case $HOSTNAME in
  kawasaki)
    #xrandr --output eDP-1 --mode 2560x1600
    #xrandr --output eDP-1 --mode 1920x1200
    xrandr --output eDP-1 --mode 1680x1050
    xrandr --output HDMI-2 --mode 2560x1440 --right-of eDP-1
    ;;
  yamaha)
    xrandr --output eDP-1 --mode 1920x1080
    xrandr --output DP-2 --mode 2560x1440 --left-of eDP-1
    ;;
esac
